version: '3.8'

services:
  bot: # Servicio para tu aplicación Node.js
    build:
      context: . # Usa el Dockerfile en el directorio actual
    ports:
      - "${PORT}:${PORT}" # Mapea el puerto del servidor al host
      - "${QR_PORT}:${QR_PORT}" # Mapea el puerto del QR al host
    env_file:
      - .env # Carga las variables desde tu archivo .env
    restart: unless-stopped # Reinicia el contenedor automáticamente si falla
    depends_on:
      - database # Espera a que el servicio database esté listo

  database: # Servicio de PostgreSQL
    image: postgres:14 # Imagen oficial de PostgreSQL
    environment:
      POSTGRES_USER: ${DB_USER} # Usuario definido en el .env
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Contraseña definida en el .env
      POSTGRES_DB: ${DB_NAME} # Nombre de la base de datos definido en el .env
    ports:
      - "${DB_PORT}:5432" # Mapea el puerto de PostgreSQL al host
    volumes:
      - db_data:/var/lib/postgresql/data # Volumen persistente para los datos
    restart: unless-stopped # Reinicia automáticamente el contenedor

volumes:
  db_data: