version: '3.8'

services:
  bot: # Servicio para tu aplicación Node.js
    build:
      context: . # Usa el Dockerfile en el directorio actual
    ports:
      - "3008:3008" # Mapea el puerto del servidor al host
      - "3010:3010" # Mapea el puerto del QR al host
    environment:
      - PORT=3008
      - QR_PORT=3010
      - DB_HOST=192.168.70.132
      - DB_PORT=5432
      - DB_NAME=zabbix
      - DB_USER=zabbix
      - DB_PASSWORD=zabbix
    restart: unless-stopped # Reinicia el contenedor automáticamente si falla
    depends_on:
      - database # Espera a que el servicio database esté listo

  database: # Servicio de PostgreSQL
    image: postgres:14 # Imagen oficial de PostgreSQL
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
    ports:
      - "5432:5432" # Mapea el puerto de PostgreSQL al host
    volumes:
      - db_data:/var/lib/postgresql/data # Volumen persistente para los datos
    restart: unless-stopped # Reinicia automáticamente el contenedor

volumes:
  db_data:
